#!/bin/bash

#    Copyright Paul Munday 2013

#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.

#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

configfile=$HOME/.nts.cfg

#Functions
help(){
cat <<EOF 

usage: $0 [OPTION]...
Clears log file
-h			prints this message

Clears the log file so check_file will not report any old notes.
EOF

    # if $1 exists and is a number 0..255 return that otherwise return 0
    if [[ -n $1 && $(echo {0..255}) =~ $1 ]]; then
            exit $1
    else
            exit 0
    fi
}

# process option arguments
while getopts "h" option; do		# w: place variable following w in $OPTARG
	case "$option" in
		h) help;;
		[?])  echo "bad option supplied" ; 
			help;;	
	esac
done

# read configuration file
declare -A conf
read_conf(){
    local file=$1
    if [[ -e $HOME/$file ]]; then
        while read line; do
            if [[ ! $line =~ "^ *#" ]]; then
                a=( $line )
                conf[${a[0]}]=$a[1]}
            fi
        done < $HOME/$file
    fi
}

read_conf $configfile

# define config values
# location of 'log file'
if [[ ${conf[logfile]} ]]; then
    logfile="${conf[logfile]}"
else
    logfile="$HOME/.notes"
fi


cat /dev/null >  $logfile
cat /dev/null > $ntsfile
